app <- ShinyDriver$new("../../")
app$snapshotInit("demo_test")

app$setInputs(load_demo = "click")
app$setInputs(params_kmax = 6)
app$setInputs(params_convthrs = 5)
app$setInputs(startNMF = "click")
# app$setInputs(`HHeat-sel_K` = "6")
# app$setInputs(`HUMAP-sel_K` = "6")
# app$setInputs(`recov-sel_K` = "6")
# app$setInputs(sel_riverRange = c(2, 6))
# app$setInputs(sel_edges_cutoff = 0.6)
# app$setInputs(mainmenu = "saveres")
# app$snapshotDownload("downloadNMFobject")
# app$setInputs(download_sel_K = "6")
# app$snapshotDownload("downloadHmatrix")
